//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PresentationMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresentationMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("code_metrics.Presentation.Resources.PresentationMessages", typeof(PresentationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string MainMenuTitle
        {
            get
            {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }

        internal static string MenuOption1
        {
            get
            {
                return ResourceManager.GetString("MenuOption1", resourceCulture);
            }
        }

        internal static string MenuOption2
        {
            get
            {
                return ResourceManager.GetString("MenuOption2", resourceCulture);
            }
        }

        internal static string MenuOption3
        {
            get
            {
                return ResourceManager.GetString("MenuOption3", resourceCulture);
            }
        }

        internal static string MenuOption4
        {
            get
            {
                return ResourceManager.GetString("MenuOption4", resourceCulture);
            }
        }

        internal static string ChooseOption
        {
            get
            {
                return ResourceManager.GetString("ChooseOption", resourceCulture);
            }
        }

        internal static string InvalidOption
        {
            get
            {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }

        internal static string Goodbye
        {
            get
            {
                return ResourceManager.GetString("Goodbye", resourceCulture);
            }
        }
    }
}
