//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Matrix.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MatrixMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MatrixMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("code_metrics.Application.Matrix.Resources.MatrixMessages", typeof(MatrixMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string Title
        {
            get
            {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        internal static string EnterRows
        {
            get
            {
                return ResourceManager.GetString("EnterRows", resourceCulture);
            }
        }

        internal static string EnterColumns
        {
            get
            {
                return ResourceManager.GetString("EnterColumns", resourceCulture);
            }
        }

        internal static string EnterInitialValue
        {
            get
            {
                return ResourceManager.GetString("EnterInitialValue", resourceCulture);
            }
        }

        internal static string InvalidRows
        {
            get
            {
                return ResourceManager.GetString("InvalidRows", resourceCulture);
            }
        }

        internal static string InvalidColumns
        {
            get
            {
                return ResourceManager.GetString("InvalidColumns", resourceCulture);
            }
        }

        internal static string MatrixCreatedSuccess
        {
            get
            {
                return ResourceManager.GetString("MatrixCreatedSuccess", resourceCulture);
            }
        }

        internal static string MatrixCreationError
        {
            get
            {
                return ResourceManager.GetString("MatrixCreationError", resourceCulture);
            }
        }

        internal static string MenuTitle
        {
            get
            {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }

        internal static string MenuOption1
        {
            get
            {
                return ResourceManager.GetString("MenuOption1", resourceCulture);
            }
        }

        internal static string MenuOption2
        {
            get
            {
                return ResourceManager.GetString("MenuOption2", resourceCulture);
            }
        }

        internal static string MenuOption3
        {
            get
            {
                return ResourceManager.GetString("MenuOption3", resourceCulture);
            }
        }

        internal static string ChooseOption
        {
            get
            {
                return ResourceManager.GetString("ChooseOption", resourceCulture);
            }
        }

        internal static string InvalidOption
        {
            get
            {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }

        internal static string Error
        {
            get
            {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }

        internal static string EnterRowIndex
        {
            get
            {
                return ResourceManager.GetString("EnterRowIndex", resourceCulture);
            }
        }

        internal static string EnterColumnIndex
        {
            get
            {
                return ResourceManager.GetString("EnterColumnIndex", resourceCulture);
            }
        }

        internal static string InvalidIndex
        {
            get
            {
                return ResourceManager.GetString("InvalidIndex", resourceCulture);
            }
        }

        internal static string EnterValueForPosition
        {
            get
            {
                return ResourceManager.GetString("EnterValueForPosition", resourceCulture);
            }
        }

        internal static string ValueSetSuccess
        {
            get
            {
                return ResourceManager.GetString("ValueSetSuccess", resourceCulture);
            }
        }

        internal static string EnterSeparator
        {
            get
            {
                return ResourceManager.GetString("EnterSeparator", resourceCulture);
            }
        }

        internal static string RowResult
        {
            get
            {
                return ResourceManager.GetString("RowResult", resourceCulture);
            }
        }

        internal static string InvalidRowsColumns
        {
            get
            {
                return ResourceManager.GetString("InvalidRowsColumns", resourceCulture);
            }
        }

        internal static string InitialValueCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("InitialValueCannotBeNull", resourceCulture);
            }
        }

        internal static string IndexOutOfBounds
        {
            get
            {
                return ResourceManager.GetString("IndexOutOfBounds", resourceCulture);
            }
        }

        internal static string ValueCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("ValueCannotBeNull", resourceCulture);
            }
        }

        internal static string RowIndexOutOfBounds
        {
            get
            {
                return ResourceManager.GetString("RowIndexOutOfBounds", resourceCulture);
            }
        }

        internal static string SeparatorCannotBeNull
        {
            get
            {
                return ResourceManager.GetString("SeparatorCannotBeNull", resourceCulture);
            }
        }
    }
}
